[book]
authors = ["RM"]
language = "en"
multilingual = false
src = "src"
title = "From CS To Financial Freedom Do It Yourself"
[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
[preprocessor.katex]
after = ["links"]


[output.html]
no-section-label = false

[output.html.fold]
enable = true
level = 1
